// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V31));
        
        string IMigrationMetadata.Id
        {
            get { return "202101080855306_V31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
